name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ujson
  - numpy
  - pip
  - spacy=2.3.7
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pip:
    - torch==1.13.1
    - --extra-index-url https://download.pytorch.org/whl/cu117
